tls: support multiple key/cert pairs, for SNI
nats-io/nats-server pull request #2029
Opened 2021-03-22 23:11 UTC by philpennock

This does not add tests or docs, this is to sound out how people feel about the
API.  If we like it, we can dress it up formally.

Turn the TLS options cert_file and key_file into list-separated paths (so
colon-delimited if on Unix, like `$PATH`); the count of entries must match, and
the keys and certs should zip together.

With this change, TLS SNI works to pick the correct cert to return for a given
connection, allowing a NATS server to have multiple identities.

/cc @nats-io/core

2021-03-23 00:17 UTC, matthiashanel requested changes
add a unit test so this functionality does not disappear?

2021-03-23 03:47 UTC, wallyqs commented
Thanks @philpennock ok sounds like we should add a field to support multiple certs optionally then:

```hcl
tls {
  certs = [{cert_file = "first.pem", key_file = "first.key"}]
}
```

2021-03-23 09:31 UTC, ripienaar commented
Agree with @wallyqs that's a lot clearer

2021-05-10 01:44 UTC, philpennock commented
It's still my intent to find time to work on the new config layout and write the tests (but I'm happy for someone else to take it if they have time).  The push just now is not me doubling-down on the quick hack proof-of-concept, it's just that I have this live at home and I wanted to install 2.2.3 so I rebased and pushed after confirming it works.

2021-09-14 01:30 UTC, derekcollison commented
What is the status here?

2022-11-12 02:50 UTC, philpennock commented
This is still useful functionality to have, but needs to be done more cleanly, as wally requested.  I'm still running with this at home (to dual-name with a .lan hostname from my personal cert authority, and with a Let's Encrypt cert for the current external IP) and we today used this patch for a fiddly migration, to be able to cut DNS over to a box at our leisure.

So the use-case is definitely there and it needs a better integration than the proof-of-concept with the path-separator strings, and tests to protect against regression.

2023-04-23 19:23 UTC, bruth commented
Is this worth revisiting and prioritizing?

2023-04-24 15:28 UTC, derekcollison commented
You should sync with @philpennock

2023-12-15 18:40 UTC, closed without merging

2023-12-15 18:40 UTC, philpennock commented
Closing in favor of Wally's #4889 which does the configuration the Right Way for nats-server, instead of the old-fashioned Unix way.  :laughing: