Stubs for WebAssembly
nats-io/nats-server pull request #2363
Opened 2021-07-14 10:21 UTC by neilalexander

This should allow NATS Server to build under the `js/wasm` target.

/cc @nats-io/core

2021-09-14 01:28 UTC, derekcollison commented
Should we be tracking this one still @neilalexander?

2021-09-14 07:38 UTC, neilalexander commented
@derekcollison If you don't mind — this PR pretty much got NATS to build for WASM but I am not 100% sure of the consequences of stubbing some of these values.

2021-12-14 09:29 UTC, gedw99 commented
> 
@derekcollison @neilalexander 
So then needs built tags, so that the code can work in browser and not in browser right ? 
Then at compile time just use the flags appropriately. 

Here is an example of what i mean: https://github.com/gioui/gio-x/tree/main/explorer

keeps everything reusable for different environments.

2021-12-15 00:05 UTC, kozlovic requested changes
I am not knowledgeable on WASM to really comment, but there are conflicts that would need to be resolved before being able to merge.
For Go 1.17 support, please *add* (not replace) build directive as such:
```
//go:build <directive>
```
So suppose you want to have:
```
// +build wasm
```
it should become:
```
//go:build wasm
// +build wasm
```
etc.. Alternatively, if you are using Go 1.17, do a "go fmt" that should add those for you.

2022-07-04 06:22 UTC, gedw99 commented
+1 Any movements on this ??

2022-07-04 18:04 UTC, derekcollison commented
Since the other PR landed with direct connect clients etc, @neilalexander do you think you could rebase on main and update copyright to 2022? Will see if we can merge for 2.9.

2022-07-04 18:06 UTC, neilalexander commented
@derekcollison Absolutely, I’ll do it first thing in the morning!

2022-07-05 16:47 UTC, kozlovic approved these changes
LGTM

2022-07-20 15:55 UTC, unicomp23 commented
what's holding up the merge?

2022-07-20 18:51 UTC, derekcollison commented
Should be ok to merge, will wait on @kozlovic

2022-07-20 19:26 UTC, merged