make error actionable when adding operator+leafnodes
nats-io/nats-server pull request #2449
Opened 2021-08-17 16:37 UTC by alsuren

There are many examples in the documentation for one half of this configuration or the other,
but none which configure a leafnode remote on an operator-authenticated cluster.

The error "operator mode requires account nkeys in remotes." is not very clear or actionable.
It was only chance googling that led us to https://github.com/nats-io/k8s/pull/286 and gave us a hint about what we needed to do.

 - [ ] Build is green in Travis CI
 - [x] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/nats-server/blob/main/LICENSE)

/cc @nats-io/core

2021-08-17 20:33 UTC, kozlovic requested changes
Reporting what staticcheck says:
```
server/leafnode.go:279:12: error strings should not end with punctuation or a newline (ST1005)
```
But more importantly, I wonder if instead of doing that, we should not make use of what @ripienaar has been introducing with errors. Should we start (in cases like that) have codes for non JetStream errors and keep adding to it when users report less than descriptive errors?
If so, R.I., would you mind showing us what it would take here to add a new error, etc..?

2021-08-18 11:29 UTC, ripienaar commented
You're right this is a good case where if we had those errors outside of JetStream would have been useful, but we are not really ready for that yet - the current work is very JS orientated and I think we're still gathering feedback on how they are to use before we consider moving them into the more senstive parts of things.

2021-08-18 14:35 UTC, kozlovic commented
@alsuren Ok, so based on RI response, I would suggest that you remove the terminal punctuation, otherwise staticcheck would reject this code change.

2021-08-18 16:22 UTC, alsuren commented
Hi. Sorry for the delay. Pushed.

```
=== RUN   TestJetStreamMaxMsgsPerAndDiscardNew/Memory
    jetstream_test.go:11193: Unexpected error: context deadline exceeded
--- FAIL: TestJetStreamMaxMsgsPerAndDiscardNew (11.98s)
    --- PASS: TestJetStreamMaxMsgsPerAndDiscardNew/File (0.68s)
    --- FAIL: TestJetStreamMaxMsgsPerAndDiscardNew/Memory (11.30s)
```
This feels unrelated, and passes locally. Is this test known to be flakey?

2021-08-18 16:26 UTC, kozlovic commented
That one yes, but maybe not this one. Please check if this test is not checking for the error that you have now changed.
```
=== RUN   TestLeafNodeOperatorBadCfg/operator_mode_requires_account_nkeys_in_remotes
    leafnode_test.go:2512: Expected error operator mode requires account nkeys in remotes but got operator mode requires account nkeys in remotes. Please add an `account` key to each remote in your `leafnodes` section, to assign it to an account. Each account value should be a 56 character public key, starting with the letter 'A'
--- FAIL: TestLeafNodeOperatorBadCfg (0.00s)
    --- PASS: TestLeafNodeOperatorBadCfg/operator_mode_does_not_allow_specifying_user_in_leafnode_config (0.00s)
    --- PASS: TestLeafNodeOperatorBadCfg/operator_mode_and_non_account_nkeys_are_incompatible (0.00s)
    --- FAIL: TestLeafNodeOperatorBadCfg/operator_mode_requires_account_nkeys_in_remotes (0.00s)
```

2021-08-18 22:21 UTC, kozlovic approved these changes
LGTM

2021-08-18 22:22 UTC, merged