Adds deterministic bucketing (i.e. 'partitioning') to subject mapping
nats-io/nats-server pull request #2888
Opened 2022-02-26 01:48 UTC by jnmoyne

Add the ability to deterministically map one or more subject tokens to a 'bucket' (or 'partition') number (uses a hashing to map the value of the token(s) to a bucket number. Works everywhere subject mapping is used (i.e. account mappings and account imports).

Mapping syntax: `$<token number(s)>%<number of buckets>`

So `$1%10` maps to the value of the bucket number (i.e. a number between `0` and `9`) for the value of $1.

You can map the values of more than one subject token using `+`, e.g.: mapping `foo.*.* : foo.$1.$2.$1+2%10` means map the combination of $1 and $2 over 10 buckets. This example will translate subject `foo.a.1` to `foo.a.1.5` (bucket number is 5).

- [ ] Link to issue, e.g. `Resolves #NNN`
 - [ ] Documentation added (if applicable)
 - [X] Tests added
 - [X] Branch rebased on top of current main (`git pull --rebase origin main`)
 - [ ] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [ ] Build is green in Travis CI
 - [X] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/nats-server/blob/main/LICENSE)
/cc @nats-io/core

2022-02-26 02:51 UTC, matthiashanel requested changes
I find `$1%10` or `$1+2%10` a pretty cryptic and not easily extensible notation.
Furthermore, new token notations retroactively constricts what subjects can look like.  

In previous discussions template tokens of the form `{{...}}` seem to be palatable and can easily be extended. For example: `{{hash(10,1}}`, `{{hash(10,1,2}}` 
If different bucketing schemes are asked for they have a place to go: `{{wasm:your-function}}`, `{{persistent-sharding(10,1)}}`
Independent of the configuration context, a user sees `{{...}}` and knows this is a substitution the server performs. 

I do not expect mappings to change often, so parsing could be done with a regex.

I do not see the unit test for stream import with local subject mapping.
Neither is there a test where multiple tokens are hashed.

2022-02-26 22:31 UTC, jnmoyne commented
Not sure what you mean by "Furthermore, new token notations retroactively constricts what subjects can look like."?

2022-02-26 22:40 UTC, jnmoyne commented
Also not sure how to do creating two accounts adding imports, creating credentials and then using those credentials to make two connections to test mapping during an import (in a unit test, I did the validate it by testing it manually and found that the same exact mapping code is used regardless of it being due to a mapping or an import). So I assumed there was no reason to repeat the same test once, once as a mapping and another one as an import, was that incorrect?

2022-02-27 10:05 UTC, jnmoyne commented
So looks like there were _no_ unit tests on subject mapping. I'm created two tests one for account mapping and another similar one for import that will test current the $-style mapping format both at the account level and import between accounts.

2022-02-28 01:53 UTC, derekcollison commented
They are tests for subject mappings for sure..

I agree with the templating idea as well, more work I know, but I think it will be worth it as @matthiashanel suggests.

2022-02-28 01:53 UTC, derekcollison commented
Also, unless very needed not to, could we squash all of these commits down to 1?

2022-02-28 21:54 UTC, jnmoyne commented
> They are tests for subject mappings for sure..

I couldn't find any... there are tests for account import that implicitly do a little bit of subject mapping, but only because they add a prefix (i.e. no mapping using token wildcards), maybe I'm not looking in the right place or missing something but as far as I can tell there were no tests for mapping token wildcards either at the account level or during an import...

> Also, unless very needed not to, could we squash all of these commits down to 1?

Appologies, it seems I managed to have a commit that has 2 parents (looks like when I did the git pull -rebase more than once maybe?) and Git will not let me squash commits because of having 2 parents...

2022-03-01 04:16 UTC, derekcollison commented
ok, check with Ivan or Phil who have much better `git fu` than I do.. ;)

2022-03-01 22:22 UTC, jnmoyne commented
Yeah, will create a new branch with just one commit which will include my upcoming changes so it's cleaner.

2022-03-01 22:22 UTC, closed without merging