Fix and test for RePub src ignored at runtime.
nats-io/nats-server pull request #3271
Opened 2022-07-15 21:01 UTC by tbeets

### Changes proposed in this pull request:

For a stream that is RePublish-enabled, the RePublish source configuration (RePublish message filter) was not being evaluated for each ingested message.  Every message ingested by stream would be (re)published.

This PR fixes and adds unit tests.

/cc @nats-io/core

2022-07-15 22:47 UTC, matthiashanel requested changes
LGTM, pending fixing the staticcheck issue as well

2022-07-17 14:58 UTC, derekcollison approved these changes
In general LGTM, we should try to optimize that match all scenario which will most likely be the more common pattern.

2022-07-17 21:08 UTC, tbeets commented
Enhanced to skip match check if Source allows any subject.  There _may_ be room to squeak more optimization by skipping the transform and simply pre-pending non-wildcard Destination tokens to the head of the message's subject hierarchy but that is net result of the transform anyway...  @derekcollison

2022-07-18 04:00 UTC, derekcollison commented on server/accounts.go
> +	if (tr.src == "" || tr.src == ">") || isSubsetMatch(tts, tr.src) {
for "" we use _EMPTY_ and their is a const for ">" as well.

2022-07-18 04:00 UTC, derekcollison commented on server/accounts.go
> +	if (tr.src == "" || tr.src == ">") || isSubsetMatch(tts, tr.src) {
If destination is empty can just use the subject as well.

2022-07-18 21:31 UTC, derekcollison approved these changes
LGTM

2022-07-18 22:02 UTC, merged