Chaos test 1
nats-io/nats-server pull request #3318
Opened 2022-08-02 00:04 UTC by mprimi

- [ ] Link to issue, e.g. `Resolves #NNN`
 - [x] Documentation added (if applicable)
 - [x] Tests added
 - [x] Branch rebased on top of current main (`git pull --rebase origin main`)
 - [x] Changes squashed to a single commit ** => intentionally split in 2 commits for easier review**
 - [ ] Build is green in Travis CI
 - [x] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/nats-server/blob/main/LICENSE)

### Changes proposed in this pull request:

- Add chaos controller
- Add "cluster bouncer" chaos monkey
- Add 2 tests that use it
- Add some utility methods

/cc @nats-io/core

2022-08-02 00:33 UTC, kozlovic requested changes
Check for my comments and notice some issues on Travis regarding fmt or unused imports. Also, may be worth (at least to experiment), add an entry in ".travis.yml" to actually trigger the tests, just to make sure that all is setup properly for that.

2022-08-02 00:33 UTC, kozlovic commented on scripts/runTestsOnTravis.sh
> +    go test -race -v -run=TestJetStreamClusterChaos ./server -count=1 -vet=off -timeout=30m -failfast
Either name this `TestJetStreamChaosCluster` or then you need to add `skip_js_cluster_chaos_tests` to the "js_cluster_tests" section above...

2022-08-02 00:33 UTC, kozlovic commented on server/jetstream_chaos_helpers_test.go
> +// Copyright 2020-2022 The NATS Authors
Since this is a new file, `2022` is enough

2022-08-02 00:33 UTC, kozlovic commented on server/jetstream_chaos_helpers_test.go
> +func init() {
Would remove that since it is empty?

2022-08-02 00:33 UTC, kozlovic commented on server/jetstream_cluster_chaos_test.go
> +// Copyright 2020-2022 The NATS Authors
Same

2022-08-02 17:37 UTC, mprimi reviewed
Thank you for the review @kozlovic 

All comments addressed.

2022-08-02 17:43 UTC, kozlovic requested changes
Still have some issues, such as:
```
# github.com/nats-io/nats-server/v2/server [github.com/nats-io/nats-server/v2/server.test]
332server/jetstream_chaos_helpers_test.go:17:2: imported and not used: "fmt"
333server/jetstream_chaos_helpers_test.go:18:2: imported and not used: "log"
334server/jetstream_chaos_helpers_test.go:20:2: imported and not used: "strings"
```

2022-08-03 00:03 UTC, kozlovic requested changes
What about adding this to .travis.yml, at least to make sure that they run correctly (even if we were to remove/comment out once it is time to merge if we want to not run them all the time):
```
    - name: "Run JetStream chaos tests"
      env: TEST_SUITE=js_chaos_tests
```
You could put that say below the line of the cluster tests `env: TEST_SUITE=js_cluster_tests`

2022-08-03 17:59 UTC, mprimi commented
@kozlovic 
> What about adding this to .travis.yml, 

I wasn't sure about adding this to the PR build critical path. Some of the tests are failing, and I need to set a large timeout once I add them.

Anyway, added now, we can always remove it later.

2022-08-03 18:08 UTC, kozlovic commented
@mprimi I just wanted your to add a new commit with that to make sure that it would trigger and run at least to make sure everything was ok. Yeah, seeing that it is 14 minutes long (just for 2 tests), maybe we don't include them by default in Travis, but devs will have options to run them locally (with naming convention). So please remove from travis.yml now that we know everything is setup correctly.

2022-08-03 21:30 UTC, mprimi commented
@kozlovic, gotch. Removed from travis

2022-08-03 22:40 UTC, kozlovic approved these changes
LGTM

2022-08-03 22:40 UTC, merged