Replace verbose API error detail with concise message
nats-io/nats-server pull request #3432
Opened 2022-09-01 16:45 UTC by tbeets

Re-placement (move) errors due to no match generated extreme-verbosity API error detail.  This PR opts for brief API error detail instead.  The mechanisms that collect verbose detail left in place if/when needed in a custom build.  

Simplification made in two places as there are two implementations of move -- one as a side effect of a stream update and the other a direct call to new move API.

/cc @nats-io/core

2022-09-01 16:47 UTC, derekcollison commented
What does the output from a NATS cli command look like now? Possible to paste example/screenshot here?

2022-09-01 16:48 UTC, derekcollison reviewed
We want more detail than this IMO. Why could it not be placed, but a summary, not the level of detail currently being sent.

2022-09-01 22:05 UTC, kozlovic requested changes
A lot of information was added to help understand why the placement failed. To be honest, I may not understand the original output myself, but completely getting rid of it may not be the right approach. We should consult with Matthias that added it, likely for a reason.

Regardless, the current test suite fails because there is a test checking for the error report.

At the very least, I wonder if we should add the special error in the server log?

2022-09-02 17:42 UTC, tbeets commented
Agree @kozlovic .  It is not obvious how to get to a "Goldilocks" message verbosity here since the factors for non-placement are several, could be multiple, and could be different for every single cluster.  That is a lot of information.  Also, as Travis caught, @matthiashanel assumes the full verbosity in validating functional tests.

I recommend we ship 2.9.0 GA as is then dialogue about approach.  From typical usage perspective (at CLI) could be better to ship detailed information from server and then allow the CLI to have verbosity option to shape the terminal output.  Need to factor in how much cluster detail to share with account owners.

2022-09-09 01:13 UTC, closed without merging