na
nats-io/nats-server pull request #3462
Opened 2022-09-09 18:30 UTC by denis-tingaikin

Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>

 - [ ] Link to issue, e.g. `Resolves #NNN`
 - [ ] Documentation added (if applicable)
 - [ ] Tests added
 - [ ] Branch rebased on top of current main (`git pull --rebase origin main`)
 - [ ] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [ ] Build is green in Travis CI
 - [ ] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/nats-server/blob/main/LICENSE)

Resolves #3461

### Changes proposed in this pull request:

Closes #3461

/cc @nats-io/core

2022-09-09 20:20 UTC, kozlovic requested changes

2022-09-09 20:20 UTC, kozlovic commented on go.mod
> +	golang.org/x/crypto v0.0.0-20210314154223-e6e6c4f2bb5b
What? This is going back to 2021? I don't think this is right... If anything, we should update to the latest.

2022-09-09 20:28 UTC, derekcollison commented on go.mod
> +	golang.org/x/crypto v0.0.0-20210314154223-e6e6c4f2bb5b
I did bump it only a day or two back, just FYI..

2022-09-09 20:30 UTC, kozlovic commented on go.mod
> +	golang.org/x/crypto v0.0.0-20210314154223-e6e6c4f2bb5b
Yes. The change looks weird since we would go back to an old revision for a CVE that affected Go 1.16 and 1.17.5-, so I asked the original poster some clarifications in the issue report. May close both if there is not a good explanation on why it would be necessary to go back to an old revision!

2022-09-09 23:49 UTC, denis-tingaikin commented on go.mod
> +	golang.org/x/crypto v0.0.0-20210314154223-e6e6c4f2bb5b
Agreed. Something is not correct. Checking.

2022-09-10 15:51 UTC, denis-tingaikin commented on go.mod
> +	golang.org/x/crypto v0.0.0-20210314154223-e6e6c4f2bb5b
We see a vulnerability 
```
	CVE-2021-44716 - (trivy):
		golang: net/http: limit growth of header canonicalization cache
		net/http in Go before 1.16.12 and 1.17.x before 1.17.5 allows uncontrolled memory consumption in the header canonicalization cache via HTTP/2 requests.
		Package name: golang.org/x/net
		Installed version: v0.0.0-20211112202133-69e39bad7dc2
		Fixed version:     v0.0.0-20211209124913-491a49abca63
```
That is going from the [ttps://github.com/nats-io/nats-server/blob/v2.9.0/go.mod#L13](https://github.com/nats-io/nats-server/blob/v2.9.0/go.mod#L13) => https://cs.opensource.google/go/x/crypto/+/c86fa9a7:go.mod;l=6

Do you have any ideas on how to fix it?

2022-09-10 16:08 UTC, ripienaar commented on go.mod
> +	golang.org/x/crypto v0.0.0-20210314154223-e6e6c4f2bb5b
I am guessing you are using a vulnerability scanner that doesn’t really understand how go works. 

But also just reading the CVE and looking what version of go we use tells you we are not vulnerable 

I suggest you run “go version -m nats-server” to see what module versions are actually used and what version go is used. 

Your tool is reporting vulnerabilities found in go.sun which isn’t relevant.

2022-09-22 16:45 UTC, kozlovic commented
@denis-tingaikin I am leaning toward closing the issues/PR regarding this. Unless there are objections, I will close "shortly"

2022-09-28 15:54 UTC, kozlovic commented
I am now closing this issue since there has not been any replies and I do believe that our dependencies were updated well past the revision that contained the fix, and also that we were not even affected in the first place.

2022-09-28 15:54 UTC, closed without merging