Enable nats-server to build on NetBSD
nats-io/nats-server pull request #3526
Opened 2022-10-06 08:30 UTC by MatthiasPetermann

Signed-off-by: Matthias Petermann <mp@petermann-it.de>

 - [x] Link to issue, e.g. `Resolves #NNN`
 - [x] Documentation added (if applicable)
 - [-] Tests added
 - [x] Branch rebased on top of current main (`git pull --rebase origin main`)
 - [-] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [?] Build is green in Travis CI
 - [x] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/nats-server/blob/main/LICENSE)

Resolves #3525

### Changes proposed in this pull request:

 - Add pse support on NetBSD (based on OpenBSD work)
 - Add (dummy) support for disk availability on NetBSD (similiar to Windows work) - I will work on real support on NetBSD later

/cc @nats-io/core

2022-10-16 09:12 UTC, MatthiasPetermann commented
Hello, thank you very much for your reply. Please also excuse my late response. I have looked again at the facts of the statfs syscall. In fact it is unfortunately the case that this is already not supported in the Golang standard library (for NetBSD). Since this would be the right place for an appropriate addition, the best choice for the nats-server at the moment is to continue with the dummy implementation, as is the case in the Windows variant. Would this be possible?

2022-10-17 15:14 UTC, kozlovic commented
> the best choice for the nats-server at the moment is to continue with the dummy implementation, as is the case in the Windows variant. Would this be possible?

So you mean as you have it in this PR, where `diskAvailable` returns `JetStreamMaxStoreDefault`, correct?

I mean, we do this for Windows (and wasm stub), so I guess this would be ok if there is no other alternative. @derekcollison what do you think?

2022-10-17 15:59 UTC, kozlovic commented
@MatthiasPetermann Ok, could you modify your PR to be made against the branch called "dev" (instead of main)? We are trying to keep changes/additions for the next release separate from the main branch. Let me know if there is any issue with that.

2022-10-19 10:48 UTC, MatthiasPetermann commented
Hello, thank you for your assessment. I have now changed the pull request to the dev branch. Please let me know if there is anything else to do. Kind regards, Matthias

2022-10-19 15:27 UTC, kozlovic requested changes
@MatthiasPetermann Sorry for not catching this early. Just a nit about copyright and then we will be able to merge. Also, if you don't mind, could you squash and have the commit's title be something like:
```
[ADDED] Ability to build on NetBSD
```
This will help us later when writing the release notes to easily see the commits that need to be included there. Thanks!

2022-10-19 15:27 UTC, kozlovic commented on server/disk_avail.go
> +//go:build !windows && !openbsd && !netbsd && !wasm
Since you modified this file, could you please add `-2022` to the very first line of this file (the copyright banner)?

2022-10-19 15:27 UTC, kozlovic commented on server/disk_avail_netbsd.go
> +// Copyright 2021 The NATS Authors
New file, so please change this year to `2022`.

2022-10-19 15:27 UTC, kozlovic commented on server/pse/pse_netbsd.go
> +// Copyright 2015-2018 The NATS Authors
Same, new file, so simply use `2022` for the year (instead of this range).

2022-10-28 16:04 UTC, MatthiasPetermann commented
Hello, thanks for the tips. I made the small changes and in the meantime also learned how to combine several previous commits ;-) I would be happy if you could look over the updated pull request again when you get a chance. If more changes are needed, please don't hesitate to write me. Kind regards, Matthias

2022-10-28 16:06 UTC, kozlovic approved these changes
LGTM. Thanks for the contribution!

2022-10-28 16:11 UTC, merged