tag policies not honored in reassignment after peer remove
nats-io/nats-server pull request #3678
Opened 2022-12-04 23:48 UTC by tbeets

Resolves issue in which tag policies (tag affinity and tag uniqueness constraint) were not honored when selecting a new peer for a stream RG to replace one just removed.  

/cc @nats-io/core

2022-12-05 00:55 UTC, derekcollison approved these changes
LGTM - One small suggestion.

2022-12-05 00:55 UTC, derekcollison commented on server/jetstream_cluster.go
> +		if ip != nil {
nil maps ok to dereference. So you can just do line 4795 direct.

https://go.dev/play/p/XLBsPw7NUBM

2022-12-05 03:16 UTC, derekcollison requested changes

2022-12-05 03:16 UTC, derekcollison commented on server/jetstream_cluster.go
> +	ip = make(map[string]struct{})
Should still conditionally create here.

2022-12-05 03:16 UTC, derekcollison commented on server/jetstream_cluster.go
> +		if ip != nil {
This is where you can just dereference, and if nil will be ok.

2022-12-05 03:20 UTC, tbeets commented on server/jetstream_cluster.go
> +	ip = make(map[string]struct{})
Yep, just noticed.  Will fix.  Thx.

2022-12-07 01:48 UTC, derekcollison approved these changes
LGTM

2022-12-07 01:50 UTC, merged