Resolves #3682: leaf node fails to reconnect, due to ping messages being held off indefinitely
nats-io/nats-server pull request #3684
Opened 2022-12-06 13:20 UTC by sandykellagher

This contribution is my original work and I license the work to the project under the [Apache 2 license](https://github.com/nats-io/nats-server/blob/main/LICENSE)

### Changes proposed in this pull request:

 - don't set cp.last in client::flushClients()
 -
 -

/cc @nats-io/core

2022-12-06 13:34 UTC, derekcollison commented
The last activity serves a role here. Agree we should be sending pings in the issue posted but not sure this is correct fix. See broken tests.

2022-12-06 13:49 UTC, sandykellagher commented
processPingTimer already ensures that pings are not delayed/held off for Gateway connections. Should it do the same for Leaf Node connections? That would be a simple change, provided it doesn't have other implications...

2022-12-06 13:56 UTC, sandykellagher commented
So I guess ConnInfo.LastActivity means either transmit or receive message. Hence the update of cp.last in flushClients().

Would it be worth having separate LastRxActivity and LastTxActivity fields?

2022-12-06 23:45 UTC, derekcollison commented
Yes I believe we should consider that for soliciting leafnodes that they always ping to make sure they trip a write to detect a dead socket.

2022-12-07 01:55 UTC, derekcollison commented
Let me know if you would want to take a stab at this, but I would be happy to take a look.

2022-12-07 13:01 UTC, derekcollison requested changes
We are close.

2022-12-07 13:01 UTC, derekcollison commented on server/client.go
> +	if c.kind != GATEWAY && c.kind != LEAF {
```suggestion
	if c.kind != GATEWAY && !c.isSpokeLeafNode() { ...
```

2022-12-07 14:25 UTC, derekcollison commented
If easier just abandon this one and create new fresh from main with the two line change we agreed upon.

2022-12-07 14:54 UTC, closed without merging