Fix Consumer not getting messages after filter update
nats-io/nats-server pull request #3829
Opened 2023-01-30 16:19 UTC by Jarema

Found during work on multiple filters

Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

/cc @nats-io/core

2023-01-30 17:00 UTC, derekcollison requested changes

2023-01-30 17:00 UTC, derekcollison commented on server/consumer.go
> +		subject := cfg.FilterSubject
Could move this to top and use subject in comparison above.

2023-01-30 17:00 UTC, derekcollison commented on server/consumer.go
> +		if cfg.FilterSubject != _EMPTY_ && subjectHasWildcard(cfg.FilterSubject) {
Could just say..

```go
if cfg.FilterSubject != _EMPTY_ {
  o.filterWC = subjectHasWildcard(cfg.FilterSubject)
}
```

2023-01-30 17:00 UTC, derekcollison commented on server/consumer.go
> +		o.mset.clsMu.Unlock()
mset does some accounting here we need to track.

See func (mset *stream) removeConsumer(o *consumer)

So might want to make stream func

```go
func (mset *Stream) swapSigSubs(o *consumer)
```

Also, make sure o.sigSub != nil before calling remove I think.

2023-01-30 21:27 UTC, Jarema commented
@derekcollison, all review comments addressed.
Thanks for pointing out the missing accounting!

2023-01-31 01:58 UTC, derekcollison approved these changes
LGTM - Small nit

2023-01-31 01:58 UTC, derekcollison commented on server/jetstream_test.go
> +
Remove newline.

2023-01-31 03:59 UTC, merged