Add data in  transit stats to TestNoRaceJetStreamClusterF3Setup
nats-io/nats-server pull request #3982
Opened 2023-03-21 10:49 UTC by Jarema

This adds information about how duration ebtween publishing a message and seeing it by the consumer.

Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

2023-03-21 11:30 UTC, neilalexander commented on server/norace_test.go
> +	var timestamps []time.Duration
Should `timestamps` be protected by a mutex too?

2023-03-21 19:14 UTC, derekcollison requested changes

2023-03-21 19:14 UTC, derekcollison commented on server/norace_test.go
> +						if ts != "" {
In server code base use _EMPTY_

2023-03-21 19:14 UTC, derekcollison commented on server/norace_test.go
> +							durations = append(durations, time.Since(duration))
For this to be effective probably need to back out publish time.

2023-04-23 20:00 UTC, bruth commented
@Jarema safe to close?

2025-04-08 11:57 UTC, neilalexander commented
Closing as old/stale.

2025-04-08 11:57 UTC, closed without merging