Add test that shows clfs behavior on dups
nats-io/nats-server pull request #5181
Opened 2024-03-06 20:27 UTC by wallyqs

2024-03-06 22:24 UTC, neilalexander approved these changes

2024-03-06 22:52 UTC, derekcollison requested changes

2024-03-06 22:52 UTC, derekcollison commented on server/jetstream_cluster_3_test.go
> +					// t.Logf("Publish Error (n:%d): %v", n, err)
Remove

2024-03-06 23:20 UTC, derekcollison commented
I think the test we want stays under any snapshot limits. Had lots of CLFS increments and then switches leaders.

2024-03-07 12:01 UTC, derekcollison requested changes

2024-03-07 12:01 UTC, derekcollison commented on server/jetstream_cluster_3_test.go
> +	time.Sleep(3 * time.Second)
Should not be neeed.

2024-03-07 12:01 UTC, derekcollison commented on server/jetstream_cluster_3_test.go
> +				_, err := js.Publish("foo", []byte("test"), nats.MsgId(fmt.Sprintf("sync:checking:%d", i)), nats.RetryAttempts(30), nats.AckWait(500*time.Millisecond))
Do multi-line.

2024-03-07 12:08 UTC, derekcollison approved these changes
LGTM

2024-03-07 12:09 UTC, neilalexander commented on server/jetstream_cluster_3_test.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
In my testing yesterday it was difficult to trip the problem straight away, it would normally need the leader to have bounced around a few times.

2024-03-07 17:07 UTC, wallyqs commented on server/jetstream_cluster_3_test.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
on v2.10.11 it would have happened around the 3rd or 4th leader election in this test

2025-02-19 22:01 UTC, alexbozhenko commented
Per @wallyqs's request I moved the test to [LongTest](https://github.com/nats-io/nats-server/blob/b17ef2b79b9087272351a57b1f5d7b5f6a98cc57/.github/workflows/long-tests.yaml#L33)

Before: 
```
# go test -race -v -list='^TestLong.*' ./server -tags=include_js_long_tests -count=1 -vet=off -timeout=60m -shuffle on -p 1 -failfast 
TestLongKVPutWithServerRestarts
TestLongNRGChainOfBlocks
TestLongClusterWorkQueueMessagesNotSkipped
ok      github.com/nats-io/nats-server/v2/server        1.083s
```

with this test:
```
# go test -race -v -list='^TestLong.*' ./server -tags=include_js_long_tests -count=1 -vet=off -timeout=60m -shuffle on -p 1 -failfast 
TestLongKVPutWithServerRestarts
TestLongNRGChainOfBlocks
TestLongClusterWorkQueueMessagesNotSkipped
TestLongClusterCLFSOnDuplicates
ok      github.com/nats-io/nats-server/v2/server        1.099s
```

```
# time go test -race -v -run='TestLongClusterCLFSOnDuplicates' ./server -tags=include_js_long_tests -count=1 -vet=off -timeout=60m -shuffle on -p 1 -failfast
-test.shuffle 1740001643186760220
=== RUN   TestLongClusterCLFSOnDuplicates
--- PASS: TestLongClusterCLFSOnDuplicates (61.77s)
PASS
ok      github.com/nats-io/nats-server/v2/server        62.970s

real    1m4,601s
user    11m31,957s
sys     1m43,788s
```

2025-02-21 23:10 UTC, wallyqs commented
Included in https://github.com/nats-io/nats-server/pull/6569

2025-02-21 23:10 UTC, closed without merging