NRG: Only reset election timeout on vote request if granting
nats-io/nats-server pull request #5315
Opened 2024-04-15 15:32 UTC by neilalexander

With the current behaviour, a node that is behind but running in the candidate state could cause nodes that are current to delay switching to the candidate state themselves because they keep resetting the election timer each time they receive a vote request.

Changing this to reset the election timeout only when granting means that we will allow other possibly more up-to-date nodes to transition to the candidate state faster.

This might explain why we've seen some unexpected delays in starting a new election after a leader has gone away.

Signed-off-by: Neil Twigg <neil@nats.io>

2024-04-16 04:08 UTC, derekcollison requested changes
I think we would need a test to show the behavior change.
This will be complex I know, but changes at this foundational layer I think need tests.

2024-04-16 17:24 UTC, mprimi commented on server/raft_test.go
> +func TestNRGUnsuccessfulVoteRequestDoesntResetElectionTimer(t *testing.T) {
Would be nice to also see a "timer resets when it should" on top of this test "timer does not reset when it shouldn't". 
But I know writing these RAFT tests is a giant pain and may not even be possible.

2024-04-17 07:02 UTC, derekcollison reviewed
Is it not possible to write a test that observes bad behavior without the timer? Meaning by watching who becomes leader in the bad case and make sure the test looks that someone else was elected?

2024-04-17 07:02 UTC, derekcollison commented on server/raft.go
> +	etlr   time.Time   // Election timer last reset time, for unit tests only
I prefer not to have things in production code that take up space that are only used for tests.

2024-04-23 01:44 UTC, derekcollison requested changes
Is there no way to prove the behavior without adding eltr? Again not a fan of test only items in production code.

2024-04-23 09:17 UTC, neilalexander commented
I'm not in love with it either but we need some state that the test can observe and I don't know what the alternative is. We have no way to introspect what the reset time or deadline of the `n.elect` timer is either before or after the vote request because Go doesn't expose that information, nor are there any other side-effects from resetting the election timer that are visible in a healthy cluster. I also tried forcing a node into an unhealthy state and checking the time taken to switch to candidate but it ended up being flakey as the time precision wasn't good enough.

2024-04-24 05:38 UTC, derekcollison approved these changes
LGTM

2024-04-24 05:39 UTC, merged