Document struct field names in stream.go
nats-io/nats-server pull request #5359
Opened 2024-04-26 07:32 UTC by jnmoyne

- Add comments to document main structure field names a bit better and improve the code accessibility.
- Rename setSourceConsumer to setupSourceConsumer (better and matches setupMirrorConsumer).

Signed-off-by: Jean-Noël Moyne <jnmoyne@gmail.com>

2024-04-26 19:47 UTC, derekcollison requested changes
Generally looks good, one minor correction needed.

2024-04-26 19:47 UTC, derekcollison commented on server/stream.go
> +	clseq      uint64            // The commit log current last sequence number.
Not the commit log, this is the run ahead of that..

2024-04-29 23:48 UTC, derekcollison approved these changes
LGTM

2024-04-29 23:50 UTC, derekcollison commented
Hey @jnmoyne can you rebase on top of main and resolve one conflict with your sourcing change?

2024-04-29 23:50 UTC, derekcollison commented
Once resolved I will pull in.

2024-04-30 00:07 UTC, jnmoyne commented
Rebased

2024-04-30 00:26 UTC, merged