Update dependencies.md
nats-io/nats-server pull request #5502
Opened 2024-06-07 10:01 UTC by Jarema

This commit updates the dependencies.md file.
It also removes the dependency version, as that is redundant to what go.mod already provides.

Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

2024-06-07 10:11 UTC, neilalexander approved these changes
LGTM

2024-06-07 14:55 UTC, derekcollison requested changes
Let's put back the server one, agree redundant but this makes scan checks only check on file in a known location regardless of language / impl/

2024-06-10 06:49 UTC, Jarema commented
@derekcollison ok, done.

2024-06-10 14:36 UTC, derekcollison approved these changes
LGTM

2024-06-10 14:37 UTC, derekcollison commented
This could have had a [ci skip] on it to avoid Travis runs.

2024-06-10 14:37 UTC, merged