[UPDATED] Add kick leafnode client functionality
nats-io/nats-server pull request #5527
Opened 2024-06-12 12:42 UTC by n-holmstedt

I was looking for a way to rebalance LeafNodes client connections (k8s loadbalancing) and found the original  #1556. I was informed at the slack that the KICK functionality in the API lacked the ability to kick leaf node connections. 

- Changed the KickClientReq struct to include client kind as per suggestion from slack. 
- Defaulted kind to "Client" to keep compability. 
- Added kind as an argument to server DisconnectClientByID
- Fetched client based on kind before closing connection. 

Tested functionality locally & ran tests without issues. Didn't get travis to work tho.

Signed-off-by: Your Name <n.holmstedt@gmail.com>

2024-06-12 13:21 UTC, derekcollison commented
I also think it should work on leafnodes.

Want some input from @ripienaar and @jnmoyne

2024-06-12 13:21 UTC, n-holmstedt commented
> I wonder if we should just keep the external API the same and if we fail looking up via the client list just check the leafnode list?

This was my initial thought as well, i might have misunderstood @ripienaar suggestions tho.

2024-06-12 13:56 UTC, ripienaar commented
There is a risk since IDs are not somehow unique 

CID 10 could be there. I aim for it but it disconnects before I kick it and then I disconnect LID 10

2024-06-12 14:18 UTC, derekcollison commented
They are all unique..

2024-06-12 14:24 UTC, ripienaar commented
> They are all unique..

Hmm, ok so if one server cannot have cid:10 and lid:10 at the same time then that's fine then, was not aware

2024-06-12 14:28 UTC, derekcollison commented
All ids are monotonic and come from same server variable under lock, so yes you can never have an id, whether CID, LID, RID or GID overlap..

2024-06-13 07:02 UTC, n-holmstedt commented
Updated the PR with the fallback to kicking leafnode client if a client id doesn't exist.

2024-06-13 09:26 UTC, ripienaar approved these changes
LGTM, I suspect the team might want a test or the existing one expanded.

2024-06-13 11:34 UTC, derekcollison requested changes
Let's add a test and also update the PR description which is no longer correct.

Thanks.

2024-06-21 21:12 UTC, derekcollison commented
Any updates here?

2024-06-25 02:30 UTC, derekcollison commented
Closing in favor of #5587

2024-06-25 02:30 UTC, closed without merging