Disable JetStream on disk errors
nats-io/nats-server pull request #6292
Opened 2024-12-22 07:44 UTC by souravagrawal

Currently, there are scenarios where NATS JetStream may encounter permission errors from the operating system when file system goes into read only mode intermittently, which can lead to an inconsistent state. In such cases, the system continues to allow publishing messages by resetting stream state, leading to a misaligned state where JetStream cannot function reliably.

This PR introduces changes to gracefully handle these permission errors and prevent NATS from continuing in an inconsistent state when:

- Flushing stream state to disk
- Deleting expired messages on startup
- Creating new block for messages
After this PR, If NATS is running in non-clustered mode, the user will be unable to issue write requests until the issue is resolved. In clustered mode, only the affected node will stop accepting requests, while the system will continue to function as long as the required quorum remains healthy.

Above mentioned behavior is controlled with a jetstream flag "stop_js_on_fs_permission" which by default is disabled.
PR potentially fixes : #6211 which leads to consumer sequence reaching higher than stream sequence.
Signed-off-by: Sourabh Agrawal souravagrawal1111@gmail.com

2024-12-24 13:34 UTC, neilalexander reviewed
We should probably have better detection of a wider array of filesystem errors like permissions etc, agreed, but I'm not entirely sure why this would be a configurable option and I don't particularly like it either.

The disk being pulled out from underneath JetStream is effectively a catastrophic operational issue and for JS to continue to try to operate in those circumstances feels problematic, i.e. with the potential for data loss that no one may even notice. Even more so in a clustered scenario where the metalayer and Raft logs are being written out to disk.

2024-12-24 14:28 UTC, souravagrawal commented
> We should probably have better detection of a wider array of filesystem errors like permissions etc, agreed, but I'm not entirely sure why this would be a configurable option and I don't particularly like it either.
> 
> The disk being pulled out from underneath JetStream is effectively a catastrophic operational issue and for JS to continue to try to operate in those circumstances feels problematic, i.e. with the potential for data loss that no one may even notice. Even more so in a clustered scenario where the metalayer and Raft logs are being written out to disk.

Thank you for taking the time to review this. 
I will remove the flag. As this is my first patch in the server, I wanted to err on the side of caution. 
Are there any other cases you think I should address as part of this?

2024-12-25 08:14 UTC, souravagrawal commented
Reopening PR, as it was closed mistakenly

2024-12-25 08:27 UTC, souravagrawal commented
> > We should probably have better detection of a wider array of filesystem errors like permissions etc, agreed, but I'm not entirely sure why this would be a configurable option and I don't particularly like it either.
> > The disk being pulled out from underneath JetStream is effectively a catastrophic operational issue and for JS to continue to try to operate in those circumstances feels problematic, i.e. with the potential for data loss that no one may even notice. Even more so in a clustered scenario where the metalayer and Raft logs are being written out to disk.
> 
> Thank you for taking the time to review this. I will remove the flag. As this is my first patch in the server, I wanted to err on the side of caution. Are there any other cases you think I should address as part of this?

Thank you for the suggestion @neilalexander. I have implemented the recommended change and removed the flag.

2025-01-02 04:35 UTC, souravagrawal commented
Hello @neilalexander, Happy New Year. 
Just following up to check if you’ve had a chance to review the changes.

2025-01-16 13:09 UTC, neilalexander requested changes
I think having the `filestore.go` call `DisableJetStream` directly may not be the best approach here. In a number of places we already surface errors up to `stream.go`, i.e. for `isOutOfSpaceErr`.

It feels like the more natural thing to do here would be to extend that same pattern, such that the stream examines surfaced errors and reacts, similar to how we do with the disk out-of-space warnings. Otherwise we end up with different types of disk errors being handled differently and that makes the code difficult to trace.

2025-01-16 13:09 UTC, neilalexander commented on server/filestore.go
> +			fs.srv.Warnf("file system permission denied while expiring msgs, disabling jetstream: %v", err)
Please make sure any log lines are capitalised/cased correctly.

2025-01-16 13:09 UTC, neilalexander commented on server/filestore.go
> +				return errFileSystemPermissionDenied
Is there a reason to do this rather than just check `os.IsPermission` further up the callstack?

2025-01-16 14:23 UTC, neilalexander commented on server/filestore.go
> +				return errFileSystemPermissionDenied
It may even make sense to define a new error-detect function for this case, similar to how we already have this in `store.go` for out-of-space:
```
func isOutOfSpaceErr(err error) bool {
	return err != nil && (strings.Contains(err.Error(), "no space left"))
}
```

2025-01-16 15:52 UTC, souravagrawal commented
> I think having the `filestore.go` call `DisableJetStream` directly may not be the best approach here. In a number of places we already surface errors up to `stream.go`, i.e. for `isOutOfSpaceErr`.
> 
> It feels like the more natural thing to do here would be to extend that same pattern, such that the stream examines surfaced errors and reacts, similar to how we do with the disk out-of-space warnings. Otherwise we end up with different types of disk errors being handled differently and that makes the code difficult to trace.

I agree; it makes sense to handle this within the same pattern. I have implemented the change as you suggested. 
However, there are a few other cases where stream-related operations, such as expireMsgs and writeFullState, are executed within a Go routine and need to be addressed in filestore.go, I believe.

2025-01-20 13:55 UTC, neilalexander commented on server/filestore.go
> +				fs.srv.DisableJetStream()
I don't _think_ `fs.srv` can be `nil` here but let's add a `fs.srv != nil` guard just in case.

2025-01-20 13:56 UTC, neilalexander commented on server/filestore.go
> +	if isPermissionError(err) {
This **must** be done after the `dios <- struct{}{}` line, otherwise the semaphore becomes unbalanced in a failure scenario.

2025-01-20 13:57 UTC, neilalexander commented on server/stream.go
> +			mset.srv.Warnf("File system permission denied while writing msg, disabling jetstream: %v", err)
Same nit here with capitalisation etc. 

`Filesystem permission denied while writing message, disabling JetStream: %v`

2025-01-20 18:56 UTC, souravagrawal commented
Thank you, @neilalexander. All the comments have been addressed.

2025-01-20 19:36 UTC, neilalexander commented
Overall looks OK, but CI is reporting `server/opts.go:6089: File is not `goimports`-ed (goimports)`. 

It doesn't actually look like anything meaningful in that file has changed, so should just be able to do `git checkout main -- server/opts.go` and re-add.

2025-01-21 03:32 UTC, souravagrawal commented
> Overall looks OK, but CI is reporting `server/opts.go:6089: File is not goimports-ed (goimports)`.
> 
> It doesn't actually look like anything meaningful in that file has changed, so should just be able to do `git checkout main -- server/opts.go` and re-add.

Hello, @neilalexander. I have made the suggested change, and CI checks are now passing.

2025-01-21 11:45 UTC, neilalexander approved these changes
LGTM

2025-01-22 13:23 UTC, merged